# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 15:24
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=ckeditor.fields.RichTextField(default='', verbose_name='About'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars', verbose_name='Avatar'),
        ),
    ]
