# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170718_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_author',
            field=models.CharField(max_length=255, null=True, verbose_name='Favourite author'),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_book',
            field=models.CharField(max_length=255, null=True, verbose_name='Favourite book'),
        ),
        migrations.AddField(
            model_name='user',
            name='novaposhta_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Novaposhta department number'),
        ),
        migrations.AddField(
            model_name='user',
            name='reading_preferences',
            field=models.CharField(max_length=255, null=True, verbose_name='Reading preferences'),
        ),
    ]
