# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170727_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(verbose_name='About'),
        ),
    ]
