# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-18 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(null=True, verbose_name='About'),
        ),
    ]
