# Generated by Django 2.0.7 on 2018-12-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181225_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fb',
            field=models.CharField(blank=True, help_text="Введіть послання на ваш профіль у FB, щоб користувачі могли з вами зв'язатись щодо обміну книгами", max_length=1000, null=True, verbose_name='Посилання на Facebook профіль'),
        ),
    ]
