# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RE', 'Register'), ('AB', 'Add book'), ('RD', 'Read book')], max_length=2, verbose_name='Type')),
                ('value', models.IntegerField(blank=True, verbose_name='Value')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'verbose_name': 'Opportunity',
            },
        ),
    ]
