# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_auto_20170811_1531'),
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='Book'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.BookReading', verbose_name='Book Reading'),
        ),
    ]
