# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-27 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20170811_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[('RE', 'Register'), ('BS', 'Book before start'), ('AB', 'Add book'), ('RD', 'Read book')], max_length=2, verbose_name='Type'),
        ),
    ]
