# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('AV', 'Available'), ('BK', 'Booked')], default='AV', max_length=2, verbose_name='Status'),
        ),
    ]
