# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreading',
            options={'verbose_name': 'Book Reading', 'verbose_name_plural': 'Book Readings'},
        ),
    ]
