# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20170623_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
