# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20170718_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreading',
            name='feelings',
            field=models.TextField(blank=True, null=True, verbose_name='Feelings'),
        ),
        migrations.AlterField(
            model_name='bookreading',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_readings', to='book.Book', verbose_name='Book'),
        ),
    ]
