# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20170727_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreading',
            name='status',
            field=models.CharField(choices=[('WO', 'Waiting for owner'), ('SP', 'Sent bu post'), ('RG', 'Reading'), ('RD', 'Read')], default='WO', max_length=2, verbose_name='Status'),
        ),
    ]
