# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_category_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.Category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.Genre', verbose_name='Genre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('UK', 'Ukrainian'), ('EN', 'English'), ('RU', 'Russian')], default=1, max_length=2, verbose_name='Language'),
            preserve_default=False,
        ),
    ]
