# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20170801_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreading',
            name='city',
            field=models.CharField(default='', max_length=255, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookreading',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookreading',
            name='novaposhta_number',
            field=models.CharField(default='', max_length=10, verbose_name='Novaposhta Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookreading',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
