# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20170805_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreading',
            name='status',
            field=models.CharField(choices=[('WO', 'Waiting for owner'), ('CO', 'Confirmed by owner'), ('SP', 'Sent by post'), ('RG', 'Reading'), ('RD', 'Read')], default='WO', max_length=2, verbose_name='Status'),
        ),
    ]
