# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20170808_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreading',
            name='date_start',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date of begining'),
        ),
    ]
