# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_auto_20170808_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreading',
            name='feelings',
        ),
        migrations.AddField(
            model_name='bookreading',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback'),
        ),
    ]
