# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 15:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_auto_20170810_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreading',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of ending'),
        ),
        migrations.AlterField(
            model_name='bookreading',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 11, 15, 31, 50, 268515, tzinfo=utc), verbose_name='Date of begining'),
            preserve_default=False,
        ),
    ]
