# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-18 15:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_auto_20170811_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.Genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('UK', 'Ukrainian'), ('EN', 'English'), ('RU', 'Russian')], default='UK', max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='', upload_to='books_image', verbose_name='Image'),
        ),
    ]
