# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-21 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_auto_20180318_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreading',
            name='before_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookreading',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of beginning'),
        ),
    ]
