# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-21 13:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_auto_20180621_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreading',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_readings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
