# Generated by Django 2.0.7 on 2018-12-27 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_book_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.Club', verbose_name='Club'),
        ),
    ]
