# Generated by Django 2.0.7 on 2019-01-02 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_auto_20181229_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreading',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_readings', to='book.Book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='bookreading',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='bookreading',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата повернення'),
        ),
        migrations.AlterField(
            model_name='bookreading',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата створення'),
        ),
        migrations.AlterField(
            model_name='bookreading',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Фідбек'),
        ),
        migrations.AlterField(
            model_name='bookreading',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Повне ім'я"),
        ),
        migrations.AlterField(
            model_name='bookreading',
            name='novaposhta_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер відділення НП'),
        ),
        migrations.AlterField(
            model_name='bookreading',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Номер Телефону'),
        ),
        migrations.AlterField(
            model_name='bookreading',
            name='status',
            field=models.CharField(choices=[('RG', 'В процесі'), ('RD', 'Прочитано')], default='RG', max_length=2, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='bookreading',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_readings', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
