# Generated by Django 2.0.7 on 2019-01-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0025_auto_20190102_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreading',
            name='fb',
            field=models.CharField(default='', max_length=1000, verbose_name='Посилання на Facebook профіль'),
            preserve_default=False,
        ),
    ]
