# Generated by Django 2.0.7 on 2018-12-26 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Член-Клуб',
                'verbose_name_plural': 'Члени-Клубу',
            },
        ),
        migrations.AlterField(
            model_name='club',
            name='manger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club', verbose_name='Клуб'),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Член'),
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(related_name='club_member', through='club.ClubMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
