# Generated by Django 2.0.7 on 2018-12-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20181226_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
