# Generated by Django 2.0.7 on 2018-12-26 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20181226_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='manger',
            new_name='manager',
        ),
    ]
