# Generated by Django 2.0.7 on 2018-12-29 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20181226_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Token')),
            ],
            options={
                'verbose_name': 'Invite',
                'verbose_name_plural': 'Invites',
            },
        ),
        migrations.AlterModelOptions(
            name='clubmember',
            options={'verbose_name': 'Член Клубу', 'verbose_name_plural': 'Члени Клубу'},
        ),
        migrations.RenameField(
            model_name='clubmember',
            old_name='member',
            new_name='user',
        ),
        migrations.AddField(
            model_name='clubinvite',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_member_invite', to='club.ClubMember', verbose_name='Член клубу'),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_members', to='club.ClubInvite', verbose_name='Invited by member'),
        ),
    ]
